services:
  aio:
    build: 
      context: ./docker
      dockerfile: Dockerfile.aio
    image: terraform-oci-kubectl-kubeseal:0.1
    #image: ghcr.io/oracle/oci-cli:latest
    # entrypoint: sh
    entrypoint: tail -f /dev/null
    volumes:
      - ./credentials/.oci:/root/.oci
      - ./credentials/.kube:/root/.kube
      - ./terraform/infra:/workspace/oci-infra
      # for services deployment and `kubeseal`
      - ./credentials/argo-ssh:/workspace/argo-ssh
      # TODO: make this even more modular!
      - ./k8s-default-ressources:/workspace/k8s-default-ressources
    # ports:
      # - 8080:8080 # for argoCD portforwarding
      # - 8181:8181 # for oci authentication portforwarding
    working_dir: /workspace
    # environment:
    #   - KUBECONFIG=~/.kube/free-k8s-config
    #   - OCI_CLI_SUPPRESS_FILE_PERMISSIONS_WARNING=True
