FROM ubuntu:24.04

ARG KUBESEAL_VERSION="0.24.2"
ARG HELM_VERSION="3.18.4"
# for multi arch builds
ARG TARGETOS
ARG TARGETARCH
# Install all packages on ubuntu based on the install description in their pages as of Q4/2025

# Install necessary packages
RUN apt-get update && apt-get install -y --no-install-recommends \
    curl \
    ca-certificates \
    wget \
    && rm -rf /var/lib/apt/lists/*

# Install OCI CLI
# RUN curl -o oci-install.sh https://raw.githubusercontent.com/oracle/oci-cli/master/scripts/install/install.sh \
#     && chmod +x oci-install.sh \
#     && ./oci-install.sh --accept-all-defaults
# Hack around to get this CLI installed 🤯
RUN apt-get update && apt-get install -y --no-install-recommends \
    python3 \
    pipx \
    && pipx install oci-cli \
    && pipx ensurepath \
    && rm -rf /var/lib/apt/lists/*

# Install Terraform (& soon Opentofu)
RUN apt-get update && apt-get install -y --no-install-recommends \
    gnupg \
    software-properties-common

RUN wget -O- https://apt.releases.hashicorp.com/gpg | \
    gpg --dearmor | \
    tee /usr/share/keyrings/hashicorp-archive-keyring.gpg > /dev/null

RUN echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(grep -oP '(?<=UBUNTU_CODENAME=).*' /etc/os-release || lsb_release -cs) main" \
    | tee /etc/apt/sources.list.d/hashicorp.list
RUN apt-get update && apt-get install -y terraform

# Install kubectl -> https://kubernetes.io/releases/download/
RUN curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/${TARGETARCH}/kubectl"
RUN chmod +x kubectl \
    && mv kubectl /usr/local/bin/

# Install kubeseal - to get the cluster running for gitOps install kubeseal as well -> https://github.com/bitnami-labs/sealed-secrets/releases/tag/v0.24.2
# https://github.com/bitnami-labs/sealed-secrets?tab=readme-ov-file#linux
RUN curl -OL "https://github.com/bitnami-labs/sealed-secrets/releases/download/v${KUBESEAL_VERSION:?}/kubeseal-${KUBESEAL_VERSION:?}-linux-${TARGETARCH}.tar.gz" \
    && tar -xvzf kubeseal-${KUBESEAL_VERSION:?}-linux-${TARGETARCH}.tar.gz kubeseal \
    && install -m 755 kubeseal /usr/local/bin/kubeseal

# Install helm - for debugging and package management
# https://github.com/argoproj/argo-cd/tree/v3.1.8 -> helm 3.18.4 | https://helm.sh/docs/intro/install/
# https://github.com/helm/helm/releases/tag/v3.18.4
# https://get.helm.sh/helm-v3.18.4-linux-arm64.tar.gz
# https://get.helm.sh/helm-v3.18.4-linux-amd64.tar.gz
RUN curl -OL "https://get.helm.sh/helm-v${HELM_VERSION:?}-linux-${TARGETARCH}.tar.gz" \
    && tar -zxvf helm-v${HELM_VERSION:?}-linux-${TARGETARCH}.tar.gz \
    && mv linux-${TARGETARCH}/helm /usr/local/bin/helm
