FROM ubuntu:24.04

ARG KUBESEAL_VERSION="0.24.2"

# Install all packages on ubuntu based on the install description in their pages as of Q4/2025

# Install necessary packages
RUN apt-get update && apt-get install -y --no-install-recommends \
    curl \
    ca-certificates \
    wget \
    && rm -rf /var/lib/apt/lists/*

# Install OCI CLI
# RUN curl -o oci-install.sh https://raw.githubusercontent.com/oracle/oci-cli/master/scripts/install/install.sh \
#     && chmod +x oci-install.sh \
#     && ./oci-install.sh --accept-all-defaults
# Hack around to get this CLI installed 🤯
RUN apt-get update && apt-get install -y --no-install-recommends \
    python3 \
    pipx \
    && pipx install oci-cli \
    && pipx ensurepath \
    && rm -rf /var/lib/apt/lists/*

# Install Terraform (& soon Opentofu)
RUN apt-get update && apt-get install -y --no-install-recommends \
    gnupg \
    software-properties-common

RUN wget -O- https://apt.releases.hashicorp.com/gpg | \
    gpg --dearmor | \
    tee /usr/share/keyrings/hashicorp-archive-keyring.gpg > /dev/null

RUN echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(grep -oP '(?<=UBUNTU_CODENAME=).*' /etc/os-release || lsb_release -cs) main" \
    | tee /etc/apt/sources.list.d/hashicorp.list
RUN apt-get update && apt-get install -y terraform

# Install kubectl
RUN curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
RUN chmod +x kubectl \
    && mv kubectl /usr/local/bin/

# Install kubeseal - to get the cluster running for gitOps install kubeseal as well
# https://github.com/bitnami-labs/sealed-secrets?tab=readme-ov-file#linux
RUN curl -OL "https://github.com/bitnami-labs/sealed-secrets/releases/download/v${KUBESEAL_VERSION:?}/kubeseal-${KUBESEAL_VERSION:?}-linux-amd64.tar.gz" \
    && tar -xvzf kubeseal-${KUBESEAL_VERSION:?}-linux-amd64.tar.gz kubeseal \
    && install -m 755 kubeseal /usr/local/bin/kubeseal
